//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "post_data")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub project: String,
    pub event_type: String,
    pub address: String,
    pub timestamp: DateTimeWithTimeZone,
    pub sign_method: String,
    pub sign: String,
    pub data: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
